config/routes.rb
Shannon::Application.routes.draw do
  get "/" => "static#home"
  get "about" => "static#about"
  get "supplement" => "static#supplement"

  get "/gallery" => "gallery#index"

  resources :photosets, :only => [:index, :show]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def index
  end

  def show
  end

end

app/controllers/photosets_controller.rb
class PhotosetsController < ApplicationController
  UID = {:user_id => YAML.load_file("#{Rails.root}/config/flickr.yml")['flickr']['user_id']}

  caches_page :index, :show, :expires_in => 1.hour
  
  def index
    respond_to do |format|
      format.json do
        render :json => (flickr.photosets.getList(UID).map do |photoset|
          Hash[photoset].keep_if {|key, value| ["id", "title", "description"].include? key }
          .merge("thumbnailUrl" => load_thumbnail(photoset))
        end)
      end
    end
  end

  def show
    respond_to do |format|
      format.json do
        render :json => {
            :id => params[:id],
            :photos => (flickr.photosets.getPhotos(:photoset_id => params[:id], :extras => "url_sq,url_o")["photo"]
                          .map do |photo|
              {:url => photo["url_o"], :thumbnail_url => photo["url_sq"]}
            end)}
      end
    end
  end

  private
  def load_thumbnail photoset
    "http://farm#{photoset["farm"]}.static.flickr.com/#{photoset["server"]}/#{photoset["primary"]}_#{photoset["secret"]}_s.jpg"
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home

  end

  def about

  end

  def supplement

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def handlebars_include template_name
    template = IO.read File.join(Rails.root, "app/sproutcore/templates", "#{template_name}.handlebars")
    template.html_safe
  end
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/gallery/index.html.erb
<%= handlebars_include "gallery" %>

app/views/gallery/show.html.erb
<h1>Gallery#show</h1>
<p>Find me in app/views/gallery/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shannon</title>
  <%= stylesheet_link_tag 'screen.css', :media => 'screen, projection' %>
  <%= stylesheet_link_tag 'print.css', :media => 'print' %>
  <!--[if lt IE 8]>
    <%= stylesheet_link_tag 'ie.css', :media => 'screen, projection' %>
  <![/endif]-->
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <%= link_to "Gallery", gallery_path %>
    <%= link_to "About", about_path %>
    <%= link_to "Supplement", supplement_path %>
  </nav>

<%= yield %>

  <%= javascript_include_tag "app" %>
</body>
</html>